#!/usr/bin/env node

import { spawnSync as spawn } from 'child_process';
import themes from '../themes.js';

for (const theme of themes) {
  const args = [ 'app', ...process.argv.slice(2), '--temporary-site', `--theme=${theme.value}` ];
  const result = spawn('node', args, {
    encoding: 'utf8',
    stdio: 'inherit'
  });
  if (result.status !== 0) {
    throw new Error(result.status || ('exited on signal ' + result.signal));
  }
}
